In [1]:
import numpy as np
np.__version__

'1.17.3'

In [5]:
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 첫 다섯 개 요소
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
# index 5 다음의 요소들
x[5:]

array([5, 6, 7, 8, 9])

In [8]:
# 중간 하위 배열
x[4:7]

array([4, 5, 6])

In [9]:
# 하나 걸러 하나씩의 요소로 구성된 배열
x[::2]

array([0, 2, 4, 6, 8])

In [10]:
# index 1 에서 시작해 하나 걸러 하나씩 요소로 구성된 배열
x[1::2]

array([1, 3, 5, 7, 9])

In [11]:
# 모든 요소를 거꾸로 나열
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
# index 5부터 하나 걸러 하나씩 요소를 거꾸로 나열
x[5::-2]

array([5, 3, 1])

In [16]:
x2 = np.random.randint(20, size=(3,4))
x2

array([[18,  0, 12,  1],
       [15, 19,  2, 15],
       [ 0, 14, 13,  0]])

In [17]:
# 두 개의 행, 세 개의 열
x2[:2, :3]

array([[18,  0, 12],
       [15, 19,  2]])

In [18]:
# 모든 행, 한 열 걸러 하나씩
x2[:3, ::2]

array([[18, 12],
       [15,  2],
       [ 0, 13]])

In [19]:
# 하위 배열 차원을 역으로 변환
x2[::-1, ::-1]

array([[ 0, 13, 14,  0],
       [15,  2, 19, 15],
       [ 1, 12,  0, 18]])

In [22]:
# 첫 번째 열 조회
print(x2[:, 0])

[18 15  0]


In [23]:
# 첫 번째 행 조회
print(x2[0, :])

[18  0 12  1]


In [24]:
# 간결하게 행 조회
print(x2[0])

[18  0 12  1]


In [25]:
# 배열 슬라이스가 배열 데이터의 사본(copy)이아니라 뷰(view)를 반환한다.
# Numpy 슬라이싱이 파이썬 리스트 슬라이싱과 다른 점 중 하나
print(x2)

[[18  0 12  1]
 [15 19  2 15]
 [ 0 14 13  0]]


In [27]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[18  0]
 [15 19]]


In [28]:
# 하위 배열을 수정하면 원래 배열이 변경되는 것을 볼 수 있다.
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [15 19]]


In [29]:
# 큰 데이터세트를 다룰 때 기반 데이터 버퍼를 복사하지 않아도
# 이 데이터의 일부에 접근하고 처리할 수 있다는 뜻
print(x2)

[[99  0 12  1]
 [15 19  2 15]
 [ 0 14 13  0]]


In [34]:
# 명시적으로 복사하고 싶을 때는 copy() 메소드를 사용한다.
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [15 19]]


In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  0]
 [15 19]]
[[99  0 12  1]
 [15 19  2 15]
 [ 0 14 13  0]]


In [39]:
# 배열 재구조화 reshape() 메소드
# 아래의 코드가 동작하려면 초기 배열의 규모가
# 형상이 변경된 배열의 규모와 일치해야 한다.
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
x = np.array([1, 2, 3])

In [41]:
# reshape을 이용한 행 벡터
x.reshape((1, 3))

array([[1, 2, 3]])

In [43]:
# newaxis를 이용한 행 벡터
x[np.newaxis, :]

array([[1, 2, 3]])

In [44]:
# reshape을 이용한 열 벡터
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [45]:
# newaxis를 이용한 열 벡터
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [47]:
# 배열 연결
# NumPy에서는 주로 np.concatenate, np.vstack, np.hstack 루틴을 이용해
# 두 배열을 결합하거나 연결한다.
# np.concatenate는 튜플이나 배열의 리스트를 첫 번째 인수로 취한다.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [48]:
# 또 한 번에 두 개 이상의 배열을 연결할 수도 있다.
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [50]:
# np.concatenate는 2차원 배열에서도 사용할 수 있다.
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [51]:
# 첫 번째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
# 두 번째 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
# 혼합된 차원의 배열로 작업할 때는
# np.vstack(수직 스택, vertical stack)과 np.hastack(수평 스택, horizontal stack)
# 함수를 사용하는 것이 더 명확하다.
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])

In [54]:
# 배열을 수직으로 쌓음
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
# 배열을 수평으로 쌓음
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [60]:
# 배열 분할하기
# np.split, np.hsplit, np.vsplit 함수로 구현된다.
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [61]:
# N개의 분할점은 N + 1개의 하위 배열을 만든다.
# 관련 함수인 np.hsplit와 np,vsplit은 서로 비슷하다.
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [63]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
