# NumPy & SciPy

NumPy는 숫자뿐만 아니라 사용자 정의 레코드도 저장할 수 있는 다차원 동형 배열 빛 행렬을 구현하고 요소 단위에서 효율적으로 연산할 수 있게 해준다.
SciPy는 NumPy를 기반으로 작성된 라이브러리로서, 선형대수학, 수치해석, 통계학에 나오는 여러 과학 계산 알고리즘을 제공한다.

In [1]:
import numpy

In [2]:
a = numpy.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
type(a)

numpy.ndarray

In [6]:
# 배열의 차원을 살펴본다.
# 이 배열은 12개의 요소를 가진 1차원 배열이다.
a.shape

(12,)

In [7]:
a.shape = 3, 4

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[2]

array([ 8,  9, 10, 11])

In [10]:
a[2, 1]

9

In [11]:
a[:, 1]

array([1, 5, 9])

In [12]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [20]:
a[:, 1]

array([1, 5, 9])

In [23]:
floats = numpy.array([3016362.69195522, 545281.10514262, 4566560.44373946])

In [24]:
floats

array([3016362.69195522,  545281.10514262, 4566560.44373946])

In [25]:
floats *= .5

In [26]:
floats

array([1508181.34597761,  272640.55257131, 2283280.22186973])

In [27]:
# 고정밀 성능 측정 타이머를 import 한다 (python 3.3부터 가능)
from time import perf_counter as pc

In [31]:
# Sample Data로 float형 천만개의 데이터가 있어야 하는데,
# 없으므로, 결과는 40ms가 안걸렸다고 한다.
t0 = pc(); floats /= 3; pc() - t0

8.160000015777769e-05